[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts", 
    "@foundry-devops=lib/foundry-devops/src",
    "@ERC721A=lib/ERC721A",
]

fs_permissions = [
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]
